# docker-compose.yml

version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webnet

  backend:
    build: ./backend
    container_name: backend
    restart: always
    volumes:
      - ./backend:/usr/src/app
      - static:/usr/src/app/static
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    networks:
      - webnet

  frontend:
    build: ./frontend
    container_name: frontend
    command: ["npm", "run", "dev"]
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    networks:
      - webnet

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - static:/usr/src/app/static
    depends_on:
      - backend
      - frontend
    networks:
      - webnet

volumes:
  postgres_data:
  static:

networks:
  webnet:
